## HOME ##
-- How many ongoing experiments, researchers, institutions, and facilities are involved?
SELECT COUNT(experiment.experimentId) FROM experiment;
SELECT COUNT(researcher.researcherId) FROM researcher;
SELECT COUNT(institution.instId) FROM institution;
SELECT COUNT(facility.facId) FROM facility;

-- What are the most recent experiments by start date?
SELECT e.experimentId, e.experimentTitle, e.experimentStatus,
               r.researcherName
FROM experiment e
JOIN researcher r ON e.leadResearcherId = r.researcherId
ORDER BY e.globalStartDate DESC LIMIT 5;

## ALL EXPERIMENTS##
-- What are the names, lead researchers, and details of each experiment? 
SELECT e.experimentId, e.experimentTitle, e.experimentStatus,
               e.globalStartDate, e.globalEndDate,
               r.researcherName, i.instName
FROM experiment e
JOIN researcher r ON e.leadResearcherId = r.researcherId
JOIN institution i ON r.instId = i.instId
ORDER BY e.experimentId;

## ADD & EDIT/UPDATE, DELETE EXPERIMENT ## 
# see experiment -> add experiment 
# see experiment -> click on an experiment -> edit 
# experiment -> click on experiment -> edit-> delete

## EXPERIMENT DETAIL ##
--Which researchers lead each experiment, and what institution are they from? (experiments -> click on an experiment)
SELECT e.*, r.researcherName, r.role, i.instName
FROM experiment e
JOIN researcher r ON e.leadResearcherId = r.researcherId
JOIN institution i ON r.instId = i.instId;
--WHERE e.experimentId = ?

--Which equipment is allocated to each experiment? (experiments-> click on an experiment -> equipment)
 SELECT eq.equipName, eq.equipMethod, eq.equipDescript, eq.isMove, eq.isReconfig,
               f.facName
FROM equipment_allocation ea
JOIN equipment eq ON eq.equipId = ea.equipId
LEFT JOIN equip_assignment eas ON eas.equipId = eq.equipId
LEFT JOIN facility f ON f.facId = eas.facId
--WHERE ea.experimentId = ?
ORDER BY eq.equipName;

-- What tech staff are assigned to each experiment? (experiments-> click on an experiment -> assigned staff)
SELECT DISTINCT ts.staffName, ts.staffRole
FROM usage u
JOIN staff_usage su ON su.usageId = u.usageId
JOIN tech_staff ts ON ts.staffId = su.staffId
--WHERE u.experimentId = ?
ORDER BY ts.staffName;

-- What facilities are being used by each experiment?  (experiments-> click on an experiment -> facilities)
SELECT f.facName, f.facPurp, f.fConfigName, fa.allocStartDate, fa.allocEndDate
FROM facility_allocation fa
JOIN facility f ON fa.facId = f.facId
--WHERE fa.experimentId = ?
ORDER BY f.facName;

-- What charges were generated by each experiment?  (experiments-> click on an experiment -> charges)
SELECT c.chargeId, c.chargeStatus, c.baseAmount, c.finalAmount,
               ba.deptName, ba.accountType
FROM charge c
JOIN usage u ON c.usageId = u.usageId
JOIN billing_account ba ON c.responsibleAccountId = ba.accountId
--WHERE u.experimentId = ?
ORDER BY c.chargeId;

## RESEARCHERS & TECH STAFF ##
-- What is each individual's role, and what institution do they belong to? (researchers and staff -> first table)
 SELECT r.researcherId, r.researcherName, r.role, i.instName, e.experimentTitle
FROM researcher r
JOIN institution i ON r.instId = i.instId
LEFT JOIN experiment e ON e.leadResearcherId = r.researcherId
GROUP BY r.researcherId
ORDER BY r.researcherName;

-- same thing for tech staff (second table)
 SELECT staffName, staffRole
FROM tech_staff
ORDER BY staffName;

## FACILITIES ## 
-- What is the purpose, configuration, and institution of each, and how many pieces of 
-- equipment and experiments are assigned to each?
SELECT f.facId, f.facName, f.facPurp, f.fConfigName, i.instName,
               COUNT(DISTINCT ea.equipId) as equipCount,
               COUNT(DISTINCT fa.experimentId) as expCount
FROM facility f
LEFT JOIN institution i ON f.instId = i.instId
LEFT JOIN equip_assignment ea ON ea.facId = f.facId
LEFT JOIN facility_allocation fa ON fa.facId = f.facId
GROUP BY f.facId
ORDER BY f.facName;

## EQUIPMENT ##
--Which equipment is assigned to which facility? (equipment tab)
SELECT equipment.equipId,
equipment.equipName,
facility.facName
FROM equipment
JOIN equip_assignment ON equip_assignment.equipId = equipment.equipId
JOIN facility ON facility.facId = equip_assignment.facId
ORDER BY equipment.equipId;

## BILLING ##
--What invoices were generated in any given billing period? (billing -> first table)
SELECT inv.invoiceId, inv.invoiceDate, inv.invoiceStatus,
               ba.deptName, ba.accountType,
               SUM(il.lineAmount) AS invoiceTotal
FROM invoice inv
JOIN billing_account ba ON inv.accountId = ba.accountId
JOIN invoice_line il ON il.invoiceId = inv.invoiceId
--WHERE inv.periodId = ?
GROUP BY inv.invoiceId
ORDER BY inv.invoiceId;

--What is the total invoiced amount by institution in any given quarter?
SELECT institution.instId,
institution.instName,
SUM (invoice_line.lineAmount) AS totalInvoiced
FROM invoice
JOIN billing_period ON invoice.periodId =billing_period.periodId
JOIN billing_account ON invoice.accountId = billing_account.accountId
JOIN institution ON billing_account.InstId = institution.instId
JOIN invoice_line ON invoice.invoiceId = invoice_line.invoiceId
--WHERE billing_period.periodStartDate >= ? AND billing_period.periodEndDate <=?
GROUP BY institution.instId, institution.instName
ORDER BY totalInvoiced DESC;

-- What are the charges by experiment?(second table)
SELECT u.experimentId, e.experimentTitle,
               COUNT(c.chargeId) AS chargeCount,
               SUM(c.finalAmount) AS totalAmount
FROM charge c
JOIN usage u ON c.usageId = u.usageId
JOIN experiment e ON e.experimentId = u.experimentId
GROUP BY u.experimentId, e.experimentTitle
ORDER BY totalAmount DESC;

-- What does institutional spending look like by quarter?
SELECT i.instName,
               SUM(il.lineAmount) AS totalInvoiced,
               COUNT(DISTINCT inv.invoiceId) AS invoiceCount
FROM invoice inv
JOIN billing_period bp ON inv.periodId = bp.periodId
JOIN billing_account ba ON inv.accountId = ba.accountId
JOIN institution i ON ba.InstId = i.instId
JOIN invoice_line il ON inv.invoiceId = il.invoiceId
--WHERE bp.periodStartDate >= ? AND bp.periodEndDate <= ?
GROUP BY i.instId, i.instName
ORDER BY totalInvoiced DESC;


